<?php
include('header.php');
$data = 'var gdpData = {
        "AF": 1,
        "AL": 1,
        "DZ": 1,
        "AO": 1,
        "AG": 1,
        "AR": 1,
        "AM": 1,
        "AU": 1,
        "AT": 1,
        "AZ": 1,
        "BS": 1,
        "BH": 1,
        "BD": 1,
        "BB": 1,
        "BY": 1,
        "BE": 1,
        "BZ": 1,
        "BJ": 1,
        "BT": 1,
        "BO": 1,
        "BA": 1,
        "BW": 1,
        "BR": 1,
        "BN": 1,
        "BG": 1,
        "BF": 1,
        "BI": 1,
        "KH": 1,
        "CM": 1,
        "CA": 1,
        "CV": 1,
        "CF": 1,
        "TD": 1,
        "CL": 1,
        "CN": 1,
        "CO": 1,
        "KM": 1,
        "CD": 1,
        "CG": 1,
        "CR": 1,
        "CI": 1,
        "HR": 1,
        "CY": 1,
        "CZ": 1,
        "DK": 1,
        "DJ": 1,
        "DM": 1,
        "DO": 1,
        "EC": 1,
        "EG": 1,
        "SV": 1,
        "GQ": 1,
        "ER": 1,
        "EE": 1,
        "ET": 1,
        "FJ": 1,
        "FI": 1,
        "FR": 1,
        "GA": 1,
        "GM": 1,
        "GE": 1,
        "DE": 1,
        "GH": 1,
        "GR": 1,
        "GD": 1,
        "GT": 1,
        "GN": 1,
        "GW": 1,
        "GY": 1,
        "HT": 1,
        "HN": 1,
        "HK": 1,
        "HU": 1,
        "IS": 1,
        "IN": 1,
        "ID": 1,
        "IR": 1,
        "IQ": 1,
        "IE": 1,
        "IL": 1,
        "IT": 1,
        "JM": 1,
        "JP": 1,
        "JO": 1,
        "KZ": 1,
        "KE": 1,
        "KI": 1,
        "KR": 1,
        "KW": 1,
        "KG": 1,
        "LA": 1,
        "LV": 1,
        "LB": 1,
        "LS": 1,
        "LR": 1,
        "LY": 1,
        "LT": 1,
        "LU": 1,
        "MK": 1,
        "MG": 1,
        "MW": 1,
        "MY": 1,
        "MV": 1,
        "ML": 1,
        "MT": 1,
        "MR": 1,
        "MU": 1,
        "MX": 1,
        "MD": 1,
        "MN": 1,
        "ME": 1,
        "MA": 1,
        "MZ": 1,
        "MM": 1,
        "NA": 1,
        "NP": 1,
        "NL": 1,
        "NZ": 1,
        "NI": 1,
        "NE": 1,
        "NG": 1,
        "NO": 1,
        "OM": 1,
        "PK": 1,
        "PA": 1,
        "PG": 1,
        "PY": 1,
        "PE": 1,
        "PH": 1,
        "PL": 1,
        "PT": 1,
        "QA": 1,
        "RO": 1,
        "RU": 1,
        "RW": 1,
        "WS": 1,
        "ST": 1,
        "SA": 1,
        "SN": 1,
        "RS": 1,
        "SC": 1,
        "SL": 1,
        "SG": 1,
        "SK": 1,
        "SI": 1,
        "SB": 1,
        "ZA": 1,
        "ES": 1,
        "LK": 1,
        "KN": 1,
        "LC": 1,
        "VC": 1,
        "SD": 1,
        "SR": 1,
        "SZ": 1,
        "SE": 1,
        "CH": 1,
        "SY": 1,
        "TW": 1,
        "TJ": 1,
        "TZ": 1,
        "TH": 1,
        "TL": 1,
        "TG": 1,
        "TO": 1,
        "TT": 1,
        "TN": 1,
        "TR": 1,
        "TM": 1,
        "UG": 1,
        "UA": 1,
        "AE": 1,
        "GB": 1,
        "US": 1,
        "UY": 1,
        "UZ": 1,
        "VU": 1,
        "VE": 1,
        "VN": 1,
        "YE": 1,
        "ZM": 1,
        "ZW": 1
    };';
$countrycodes = array (
    'AF' => 'Afghanistan',
    'AX' => 'Åland Islands',
    'AL' => 'Albania',
    'DZ' => 'Algeria',
    'AM' => 'Armenia',
    'AS' => 'American Samoa',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antarctica',
    'AG' => 'Antigua and Barbuda',
    'AR' => 'Argentina',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azerbaijan',
    'BS' => 'Bahamas',
    'BH' => 'Bahrain',
    'BD' => 'Bangladesh',
    'BB' => 'Barbados',
    'BY' => 'Belarus',
    'BE' => 'Belgium',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BO' => 'Bolivia',
    'BA' => 'Bosnia and Herzegovina',
    'BW' => 'Botswana',
    'BV' => 'Bouvet Island',
    'BR' => 'Brazil',
    'IO' => 'British Indian Ocean Territory',
    'BN' => 'Brunei Darussalam',
    'BG' => 'Bulgaria',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'KH' => 'Cambodia',
    'CM' => 'Cameroon',
    'CA' => 'Canada',
    'CV' => 'Cape Verde',
    'KY' => 'Cayman Islands',
    'CF' => 'Central African Republic',
    'TD' => 'Chad',
    'CL' => 'Chile',
    'CN' => 'China',
    'CX' => 'Christmas Island',
    'CC' => 'Cocos (Keeling) Islands',
    'CO' => 'Colombia',
    'KM' => 'Comoros',
    'CG' => 'Congo',
    'CD' => 'Zaire',
    'CK' => 'Cook Islands',
    'CR' => 'Costa Rica',
    'CI' => 'Côte D\'Ivoire',
    'HR' => 'Croatia',
    'CU' => 'Cuba',
    'CY' => 'Cyprus',
    'CZ' => 'Czech Republic',
    'DK' => 'Denmark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominica',
    'DO' => 'Dominican Republic',
    'EC' => 'Ecuador',
    'EG' => 'Egypt',
    'SV' => 'El Salvador',
    'GQ' => 'Equatorial Guinea',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'ET' => 'Ethiopia',
    'FK' => 'Falkland Islands (Malvinas)',
    'FO' => 'Faroe Islands',
    'FJ' => 'Fiji',
    'FI' => 'Finland',
    'FR' => 'France',
    'GF' => 'French Guiana',
    'PF' => 'French Polynesia',
    'TF' => 'French Southern Territories',
    'GA' => 'Gabon',
    'GM' => 'Gambia',
    'GE' => 'Georgia',
    'DE' => 'Germany',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Greece',
    'GL' => 'Greenland',
    'GD' => 'Grenada',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GG' => 'Guernsey',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HM' => 'Heard Island and Mcdonald Islands',
    'VA' => 'Vatican City State',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong',
    'HU' => 'Hungary',
    'IS' => 'Iceland',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Iran, Islamic Republic of',
    'IQ' => 'Iraq',
    'IE' => 'Ireland',
    'IM' => 'Isle of Man',
    'IL' => 'Israel',
    'IT' => 'Italy',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JE' => 'Jersey',
    'JO' => 'Jordan',
    'KZ' => 'Kazakhstan',
    'KE' => 'KENYA',
    'KI' => 'Kiribati',
    'KP' => 'Korea, Democratic People\'s Republic of',
    'KR' => 'Korea, Republic of',
    'KW' => 'Kuwait',
    'KG' => 'Kyrgyzstan',
    'LA' => 'Lao People\'s Democratic Republic',
    'LV' => 'Latvia',
    'LB' => 'Lebanon',
    'LS' => 'Lesotho',
    'LR' => 'Liberia',
    'LY' => 'Libyan Arab Jamahiriya',
    'LI' => 'Liechtenstein',
    'LT' => 'Lithuania',
    'LU' => 'Luxembourg',
    'MO' => 'Macao',
    'MK' => 'Macedonia, the Former Yugoslav Republic of',
    'MG' => 'Madagascar',
    'MW' => 'Malawi',
    'MY' => 'Malaysia',
    'MV' => 'Maldives',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MH' => 'Marshall Islands',
    'MQ' => 'Martinique',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Mexico',
    'FM' => 'Micronesia, Federated States of',
    'MD' => 'Moldova, Republic of',
    'MC' => 'Monaco',
    'MN' => 'Mongolia',
    'ME' => 'Montenegro',
    'MS' => 'Montserrat',
    'MA' => 'Morocco',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NP' => 'Nepal',
    'NL' => 'Netherlands',
    'AN' => 'Netherlands Antilles',
    'NC' => 'New Caledonia',
    'NZ' => 'New Zealand',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'NF' => 'Norfolk Island',
    'MP' => 'Northern Mariana Islands',
    'NO' => 'Norway',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestinian Territory, Occupied',
    'PA' => 'Panama',
    'PG' => 'Papua New Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PH' => 'Philippines',
    'PN' => 'Pitcairn',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'QA' => 'Qatar',
    'RE' => 'Réunion',
    'RO' => 'Romania',
    'RU' => 'Russia',
    'RW' => 'Rwanda',
    'SH' => 'Saint Helena',
    'KN' => 'Saint Kitts and Nevis',
    'LC' => 'Saint Lucia',
    'PM' => 'Saint Pierre and Miquelon',
    'VC' => 'Saint Vincent and the Grenadines',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'Sao Tome and Principe',
    'SA' => 'Saudi Arabia',
    'SN' => 'Senegal',
    'RS' => 'Serbia',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SK' => 'Slovak Republic',
    'SI' => 'Slovenia',
    'SB' => 'Solomon Islands',
    'SO' => 'Somalia',
    'ZA' => 'South Africa',
    'GS' => 'South Georgia and the South Sandwich Islands',
    'ES' => 'Spain',
    'LK' => 'Sri Lanka',
    'SD' => 'Sudan',
    'SR' => 'Suriname',
    'SJ' => 'Svalbard and Jan Mayen',
    'SZ' => 'Swaziland',
    'SE' => 'Sweden',
    'CH' => 'Switzerland',
    'SY' => 'Syrian Arab Republic',
    'TW' => 'Taiwan, Province of China',
    'TJ' => 'Tajikistan',
    'TZ' => 'Tanzania, United Republic of',
    'TH' => 'Thailand',
    'TL' => 'Timor-Leste',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad and Tobago',
    'TN' => 'Tunisia',
    'TR' => 'Turkey',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks and Caicos Islands',
    'TV' => 'Tuvalu',
    'UG' => 'Uganda',
    'UA' => 'Ukraine',
    'AE' => 'United Arab Emirates',
    'GB' => 'United Kingdom',
    'US' => 'United States',
    'UM' => 'United States Minor Outlying Islands',
    'UY' => 'Uruguay',
    'UZ' => 'Uzbekistan',
    'VU' => 'Vanuatu',
    'VE' => 'Venezuela',
    'VN' => 'Viet Nam',
    'VG' => 'Virgin Islands, British',
    'VI' => 'Virgin Islands, U.S.',
    'WF' => 'Wallis and Futuna',
    'EH' => 'Western Sahara',
    'YE' => 'Yemen',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe',
);
foreach($countrycodes as $code => $country)
      $data = str_replace('"'.$code.'": 1','"'.$code.'": '.$con->query("SELECT COUNT(*) FROM bots WHERE country=\"$country\"")->fetch()[0],$data);
$total = $con->query("SELECT COUNT(*) FROM bots")->fetch()[0];
?>
 <div id="content">
    <div id="content-content">

        <div id="content-box-map">
            <div id="map" class="jvectormap-container"></div>
        </div>
    </div>

    <div id="statboxes">
        <div id="stat-box">
            <div id="stat-header">
                <div id="stat-title">
                    OS Statistics
                </div>
            </div>

            <div id="stat-content">
                <div id="stat-text">
                    <table>
                        <th>Rank</th>
                        <th>OS</th>
                        <th>Bots</th>
                        <th>Percent</th>
                        <?php
                        $index = 1;
                        foreach($con->query("SELECT os, COUNT(os) as count FROM bots GROUP BY os ORDER BY count DESC LIMIT 5")
                                    ->fetchAll(PDO::FETCH_OBJ) as $row) {
                            $count = number_format($row->count/($total/100),1);
                            echo "
                        <tr>
                            <td>$index</td>
                            <td>$row->os</td>
                            <td>$row->count</td>
                            <td>$count%</td>
                        </tr>";
                            $index++;
                        }?>
                    </table>
                </div>
            </div>
        </div>

        <div id="stat-box2">
            <div id="stat-header">
                <div id="stat-title">
                    Country Statistics
                </div>
            </div>

            <div id="stat-content">
                <div id="stat-text">
                    <table>
                        <th>Rank</th>
                        <th>Country</th>
                        <th>Bots</th>
                        <th>Percent</th>
                        <?php
                        $index = 1;
                        foreach($con->query("SELECT country, COUNT(country) as count FROM bots GROUP BY country ORDER BY count DESC LIMIT 5")
                                    ->fetchAll(PDO::FETCH_OBJ) as $row) {
                            $count = number_format($row->count/($total/100),1);
                            echo "
                        <tr>
                            <td>$index</td>
                            <td>$row->country</td>
                            <td>$row->count</td>
                            <td>$count%</td>
                        </tr>";
                            $index++;
                        }?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    <?php echo $data; ?>
    $(function(){
        $('#map').vectorMap({
            map: 'world_mill_en',
            backgroundColor: 'transparent',

            series: {
                regions: [{
                    values: gdpData,
                    scale: ['#FFFFFF', '#0071A4'],
                    normalizeFunction: 'polynomial'
                }]
            },
            hoverOpacity: 0.7,
            hoverColor: false,
            onRegionTipShow: function(event, label, code){
                label.text(label.text() + " (" + gdpData[code] + ")");
            }
        });
    });
</script>
<?php
include('footer.php');
?>
